services:
  postgres:
    image: postgres:16.0
    container_name: postgres_payment
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data

  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_payment:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "6500:6500"
      - "6600:6600"
    healthcheck:
      test: ["CMD","wget","--no-verbose","--tries=1","--spider","http://localhost:6600/actuator/health"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./logs:/app/logs

volumes:
  payment_data: